### ISSUE TITLE
When using persistent volume (Azure File Share/ Azure Disk) on AKS Cluster, the application failed to read the Git hub data.

### ISSUE THREAD

**Issue by mmsajidcloud** [thoughtworks/metrik#101] opened 2021-11-16 13:01 UTC
Hello Awesome Team,

**Describe the bug**

When using persistent volume (Azure File Share/ Azure Disk) on AKS Cluster, 
the application failed to read the Git hub data, it kept on synchronizing but never loaded any data.

However if we deploy the application on AKS, with out any external volume mount,  it works fine.

**To Reproduce**

**SetUp**
1. Create a Storage class (Azure File Share) on AKS Cluster
2. Create a PVC (Persistent Volume Claim)
3. Create a deployment and mount the  /data/db on the above created PVC 
4. Create a load balancer service for accessing the application.

5. Access the application using load balancer IP, 
6. Create a new project and configure with GITHUB repo using PAT tokens.

**Expected behavior**

The application would have loaded the GITHUB data and display the charts.

**Screenshots**

![image](https://user-images.githubusercontent.com/55435593/141989065-1e2d8761-dea0-45df-9800-b72480e53308.png)

![image](https://user-images.githubusercontent.com/55435593/141988917-4fc2fe5f-f505-4705-b30b-d2821b195552.png)

**Cluster Information**

K8s Version : 1.20.7
Cloud Provider : Azure
Persistent Volume : Azure File Share / Azure Disk

**Comment by mba484** [comment] 2021-11-19 15:55
Any inputs on this will be appreciated

**Comment by hyrepo** [comment] 2021-11-23 07:54
Hi @mmsajidcloud  and @mba484, I think this may be caused by some data writing issue. After data sync, data will be written into the database, and it will be retrieved for calculation. So If data can't be written into DB then there will be no data shown in the page.

I'm not sure what happened since we don't have AKS, but you may try to check the access control of the PVC as mentioned in [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control), the access issue happens sometimes.

**Comment by mba484** [comment] 2021-12-24 09:18
Hi @hyrepo,

Thanks for coming back, we have managed to fix this by giving permission 
in the persistent storage class.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-sc
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0600
  - uid=999
  - gid=999
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS

**Comment by hyrepo** [comment] 2021-12-27 03:06
Hi @mba484 , glad to hear that, closing this issue

**Closed by hyrepo** 2021-12-27 03:06 UTC
